# Scaffolding generated by Casein v5.1.1.5

module Casein
  class ProductionsController < Casein::CaseinController

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = 'Productions'
  		@productions = Production.order(sort_order(:name)).paginate :page => params[:page]
    end

    def show
      @casein_page_title = 'View production'
      @production = Production.friendly.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new production'
    	@production = Production.new
    end

    def create
      @production = Production.new production_params

      if @production.save
        store_images(params[:production][:images])
        flash[:notice] = 'Production created'
        redirect_to casein_productions_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new production'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update production'

      @production = Production.friendly.find params[:id]

      if @production.update_attributes production_params
        delete_images
        store_images(params[:production][:images])
        flash[:notice] = 'Production has been updated'
        redirect_to casein_productions_path
      else
        flash.now[:warning] = 'There were problems when trying to update this production'
        render :action => :show
      end
    end

    def destroy
      @production = Production.friendly.find params[:id]

      @production.destroy
      flash[:notice] = 'Production has been deleted'
      redirect_to casein_productions_path
    end

    private

      def production_params
        params.require(:production).permit(:name, :synopsis, :tech_summary, :video_link, :tech_spec_link, :media_pack_link, :catagory, :slug)
      end

      def store_images(images)
        images.each{|image| @production.images.create(image: image)} if images
      end

      def delete_images
        @production.images.each do |image|
          image.destroy if params[image.id.to_s] =='delete'
        end
      end
  end
end
